import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Carousel from '../components/carousel/Carousel'

const inter = Inter({ subsets: ['latin'] })

export default function Home({response}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Carousel movies={response} top={false} />
      </main>
    </>
  )
} 

export async function getServerSideProps() {
	const res = await fetch("https://83n5sz9zvl.execute-api.us-east-1.amazonaws.com/api/v1/movies");
  const response = await res.json();
	return {
		props: {
			response,
		},
	};
}